[package]
name = "agarwal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nalgebra = "0.33.0"
ordered-float = "4.3.0"
parry3d = "0.17.1"
wasm-bindgen = "0.2.93"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"